version: "3.7" # 目前使用的版本，可以參考官網：
services: # services 關鍵字後面列出 web, redis 兩項專案中的服務
  Website:
    restart: always
    build: 
      context: ./
      dockerfile: Dockerfile # Build 在同一資料夾的 Dockerfile（描述 Image 要組成的 yaml 檔案）成 container
    image: innodiskorg/dataset-tool-website-device:v100
    container_name: dataset-tool-website-device
    environment:
      - NGINX_PORT=3006
      - BACKEND_PORT=81
      - BACKEND_SERVER=172.16.12.28
    network_mode: host

